services:
  chimera-backend:
    container_name: chimera-backend
    image: ${BACKEND_IMAGE:-ericogr/chimera-cards-backend}:${TAG:-latest}
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    expose:
    - "8080"
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CHIMERA_CONFIG: /game/chimera_config.json
      CHIMERA_DB: /game/data/chimera.db
    volumes:
    - ./backend/chimera_config.json:/game/chimera_config.json:ro
    - ./backend/data:/game/data:rw
    restart: unless-stopped

  chimera-frontend:
    container_name: chimera-frontend
    image: ${FRONTEND_IMAGE:-ericogr/chimera-cards-frontend}:${TAG:-latest}
    environment:
      REACT_APP_GOOGLE_CLIENT_ID: ${REACT_APP_GOOGLE_CLIENT_ID}
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-/api}
    depends_on:
    - chimera-backend
    expose:
    - "80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  caddy:
    container_name: chimera-caddy
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    depends_on:
    - chimera-backend
    - chimera-frontend
    ports:
    - "8880:80"
    - "8443:443"
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CADDY_EMAIL: ${CADDY_EMAIL}
      DOMAIN: ${DOMAIN}
    volumes:
    - ./infrastructure/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    - ./infrastructure/caddy/data:/data
    - ./infrastructure/caddy/config:/config
    restart: unless-stopped
