version: '3.8'
services:
  chimera-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${BACKEND_IMAGE:-quimera-backend}:${TAG:-latest}
    ports:
    - "8080:8080"
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CHIMERA_CONFIG: /config/chimera_config.json
    volumes:
    - ./backend/chimera_config.json:/config/chimera_config.json:ro
    - ./backend/quimera.db:/quimera.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  chimera-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_GOOGLE_CLIENT_ID: ${REACT_APP_GOOGLE_CLIENT_ID}
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-/api}
    environment:
      - REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-/api}
    image: ${FRONTEND_IMAGE:-quimera-frontend}:${TAG:-latest}
    depends_on:
      - chimera-backend
    ports:
    - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
