#!/usr/bin/env sh
set -eu

ENV_FILE=public/env-config.js

# Only read from environment variables. Do not source .env files.
REQUIRED="REACT_APP_GOOGLE_CLIENT_ID REACT_APP_API_BASE_URL"
MISSING=""
for V in $REQUIRED; do
  if [ -z "$(printenv "$V" || true)" ]; then
    MISSING="$MISSING $V"
  fi
done

if [ -n "$(echo "$MISSING" | tr -d ' ')" ]; then
  echo "ERROR: Missing required environment variable(s):$MISSING" >&2
  echo "The frontend will not start because required runtime variables are missing." >&2
  exit 1
fi

# Both variables present — write minimal runtime config.
CLIENT_ID=$(printenv REACT_APP_GOOGLE_CLIENT_ID)
API_BASE=$(printenv REACT_APP_API_BASE_URL)

escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

CLIENT_ID_ESC=$(escape "$CLIENT_ID")
API_BASE_ESC=$(escape "$API_BASE")

cat > "$ENV_FILE" <<EOF
// This file is generated by 'make start'. Do not commit.
window._env_ = {
  "REACT_APP_GOOGLE_CLIENT_ID": "$CLIENT_ID_ESC",
  "REACT_APP_API_BASE_URL": "$API_BASE_ESC"
};
EOF

exit 0

