name: Build and publish Docker images

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
    paths:
      - 'backend/**'
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create version variables
        id: vars
        run: |
          VERSION=$(git describe --tags --dirty --always --long 2>/dev/null || echo dev)
          COMMIT=$(git rev-parse --short HEAD)
          DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          if [ -n "$(git status --porcelain)" ]; then DIRTY=true; else DIRTY=false; fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "commit=$COMMIT" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT
          echo "dirty=$DIRTY" >> $GITHUB_OUTPUT

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ericogr/chimera-cards-backend:${{ steps.vars.outputs.version }}
            ericogr/chimera-cards-backend:latest
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}
            COMMIT=${{ steps.vars.outputs.commit }}
            BUILD_DATE=${{ steps.vars.outputs.date }}
            DIRTY=${{ steps.vars.outputs.dirty }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ericogr/chimera-cards-frontend:${{ steps.vars.outputs.version }}
            ericogr/chimera-cards-frontend:latest
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}
            COMMIT=${{ steps.vars.outputs.commit }}
            BUILD_DATE=${{ steps.vars.outputs.date }}
            DIRTY=${{ steps.vars.outputs.dirty }}
            REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
            REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}
